import type { Dish } from "@/components/DishCard";

export const categories = [
  { id: "amuse-bouche", name: "AMUSE-BOUCHE", slug: "amuse-bouche" },
  { id: "entrees", name: "ENTRÉES", slug: "entrees" },
  { id: "grillades", name: "GRILLADES", slug: "grillades" },
  { id: "complements", name: "COMPLÉMENTS", slug: "complements" },
  { id: "mabokes", name: "MABOKÉS", slug: "mabokes" },
  { id: "plats-cuisiniers", name: "PLATS CUISINIERS", slug: "plats-cuisiniers" },
];

const featuredDishes: Dish[] = [
  {
    id: "assiette-tapas",
    name: "Assiette tapas",
    slug: "assiette-tapas",
    description: "Assortiment de bouchées croustillantes, beignets de poisson et bananes plantains frites.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1541529086526-db283c563270?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: true,
    category: { name: "AMUSE-BOUCHE", slug: "amuse-bouche" },
  },
  {
    id: "meli-melo",
    name: "Meli Melo",
    slug: "meli-melo",
    description: "Brochettes épicées, crevettes grillées et légumes croquants marinés.",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: false,
    category: { name: "AMUSE-BOUCHE", slug: "amuse-bouche" },
  },
  {
    id: "salade-albert",
    name: "Salade Albert",
    slug: "salade-albert",
    description: "Crudités du marché, poulet rôti, œuf dur et vinaigrette maison.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: false,
    category: { name: "ENTRÉES", slug: "entrees" },
  },
  {
    id: "salade-avocat-crevette",
    name: "Salade avocat-crevette",
    slug: "salade-avocat-crevette",
    description: "Crevettes sautées servies sur un lit d'avocats mûrs et sauce cocktail maison.",
    price: 5000,
    imageUrl: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: true,
    category: { name: "ENTRÉES", slug: "entrees" },
  },
  {
    id: "poisson-braise",
    name: "Poisson braisé",
    slug: "poisson-braise",
    description: "Capitaine ou bar braisé au charbon, mariné aux épices locales.",
    price: 7000,
    isVariablePrice: true,
    priceNote: "Selon arrivage et taille (7 000 - 12 000 FCFA)",
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: true,
    category: { name: "GRILLADES", slug: "grillades" },
  },
  {
    id: "brochette-de-poisson",
    name: "Brochette de poisson",
    slug: "brochette-de-poisson",
    description: "Poisson blanc, poivrons et oignons rouges grillés au feu de bois.",
    price: 5500,
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: false,
    category: { name: "GRILLADES", slug: "grillades" },
  },
  {
    id: "brochette-de-filet-de-boeuf",
    name: "Brochette de filet de bœuf",
    slug: "brochette-de-filet-de-boeuf",
    description: "Filet de bœuf tendre assaisonné aux herbes et braisé.",
    price: 6000,
    imageUrl: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: true,
    category: { name: "GRILLADES", slug: "grillades" },
  },
  {
    id: "poulet-de-chair-braise",
    name: "Poulet braisé aux petits légumes",
    slug: "poulet-de-chair-braise-aux-petits-legumes",
    description: "Poulet entier braisé et légumes sautés, relevés par une marinade maison.",
    price: 8000,
    imageUrl: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: true,
    category: { name: "GRILLADES", slug: "grillades" },
  },
  {
    id: "banane-fruit-du-vapeur",
    name: "Banane plantain vapeur",
    slug: "banane-fruit-du-vapeur",
    description: "Bananes plantains mûres ou vertes cuites à la vapeur douce.",
    price: 1500,
    imageUrl: "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: false,
    category: { name: "COMPLÉMENTS", slug: "complements" },
  },
  {
    id: "riz-parfume",
    name: "Riz parfumé",
    slug: "riz-parfume",
    description: "Riz blanc parfumé, idéal en accompagnement de sauces et grillades.",
    price: 1000,
    imageUrl: "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: false,
    category: { name: "COMPLÉMENTS", slug: "complements" },
  },
  {
    id: "maboke-de-capitaine",
    name: "Maboké de capitaine",
    slug: "maboke-de-capitaine",
    description: "Capitaine étouffé dans une feuille de bananier avec tomates, ciboulette et piment doux.",
    price: 8500,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: true,
    category: { name: "MABOKÉS", slug: "mabokes" },
  },
  {
    id: "maboke-de-sanglier",
    name: "Maboké de sanglier",
    slug: "maboke-de-sanglier",
    description: "Sanglier fumé cuit en papillote de feuille de bananier aux épices.",
    price: 9000,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: false,
    category: { name: "MABOKÉS", slug: "mabokes" },
  },
  {
    id: "saka-saka",
    name: "Saka-Saka",
    slug: "saka-saka",
    description: "Feuilles de manioc mijotées à l'huile de palme rouge et au poisson fumé.",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: true,
    category: { name: "PLATS CUISINIERS", slug: "plats-cuisiniers" },
  },
  {
    id: "gambas-sautees",
    name: "Gambas sautées",
    slug: "gambas-saute",
    description: "Gambas sautées au beurre d'ail, persil et citron vert.",
    price: 12000,
    imageUrl: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    isPopular: true,
    category: { name: "PLATS CUISINIERS", slug: "plats-cuisiniers" },
  },
];

type AdditionalDish = Omit<Dish, "category" | "isPopular"> & {
  categorySlug: string;
  isPopular?: boolean;
};

const additionalDishes: AdditionalDish[] = [
  { id: "salade-composee", name: "Salade composée", slug: "salade-composee", description: "Méli-mélo de tomates fraîches, concombres, maïs doux, carottes râpées et olives noires au citron.", price: 3500, imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80", categorySlug: "entrees", isAvailable: true },
  { id: "salade-avocat", name: "Salade avocat", slug: "salade-avocat", description: "Avocats tropicaux de Songolo crémeux, tranches de tomate et ciboulette fraîche assaisonnés à l'huile d'olive.", price: 3000, imageUrl: "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=600&auto=format&fit=crop&q=80", categorySlug: "entrees", isAvailable: true },
  { id: "brochette-mixte", name: "Brochette mixte", slug: "brochette-mixte", description: "Combinaison savoureuse de bœuf, poulet et crevettes grillés sur pique avec marinade barbecue piquante.", price: 6500, imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80", categorySlug: "grillades", isAvailable: true },
  { id: "brochette-de-viande", name: "Brochette de viande", slug: "brochette-de-viande", description: "Brochettes de viande de bœuf traditionnelles assaisonnées aux épices africaines.", price: 5000, imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&auto=format&fit=crop&q=80", categorySlug: "grillades", isAvailable: true },
  { id: "cuisse-de-poulet-braise", name: "Cuisse de poulet braisé", slug: "cuisse-de-poulet-braise", description: "Belle cuisse de poulet mariné braisée à cœur avec peau croustillante.", price: 4500, imageUrl: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&auto=format&fit=crop&q=80", categorySlug: "grillades", isAvailable: true },
  { id: "pomme-de-terre-frite-ou-vapeur", name: "Pomme de terre frite ou vapeur", slug: "pomme-de-terre-frite-ou-vapeur", description: "Frites dorées croustillantes ou pommes de terre fondantes cuites à la vapeur.", price: 1500, imageUrl: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80", categorySlug: "complements", isAvailable: true },
  { id: "manioc", name: "Manioc", slug: "manioc", description: "Bâton de manioc traditionnel cuit à la vapeur, ferme et savoureux.", price: 1000, imageUrl: "https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=600&auto=format&fit=crop&q=80", categorySlug: "complements", isAvailable: true },
  { id: "foufou", name: "Foufou", slug: "foufou", description: "Foufou traditionnel bien tiédi et onctueux.", price: 1000, imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80", categorySlug: "complements", isAvailable: true },
  { id: "jardiniere-de-legumes", name: "Jardinière de légumes", slug: "jardiniere-de-legumes", description: "Poêlée de légumes frais de saison au beurre d'ail (carottes, haricots verts, courgettes).", price: 2000, imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80", categorySlug: "complements", isAvailable: true },
  { id: "maboke-de-maigrenon", name: "Maboké de maigrénon", slug: "maboke-de-maigrenon", description: "Poisson Maigrénon délicat préparé à l'étouffée selon la recette ancestrale du Jardin de Bayonne.", price: 8000, imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80", categorySlug: "mabokes", isAvailable: true },
  { id: "maboke-de-mbesset", name: "Maboké de mbesset", slug: "maboke-de-mbesset", description: "Poisson Mbesset préparé à l'étouffée de feuilles traditionnelles avec brins de piment vert aromatique.", price: 8500, imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80", categorySlug: "mabokes", isAvailable: true },
  { id: "maboke-de-mbumi", name: "Maboké de mbumi", slug: "maboke-de-mbumi", description: "Poisson d'eau douce Mbumi cuit à la vapeur des feuilles de bananier.", price: 8000, imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80", categorySlug: "mabokes", isAvailable: true },
  { id: "maboke-de-maroka", name: "Maboké de maroka", slug: "maboke-de-maroka", description: "Poisson Maroka mariné aux condiments locaux étouffé sous braises douces.", price: 8000, imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80", categorySlug: "mabokes", isAvailable: true },
  { id: "maboke-mbito", name: "Maboké mbito", slug: "maboke-mbito", description: "Poisson Mbito sélectionné cuit au jus naturel dans son emballage de feuille.", price: 8500, imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80", categorySlug: "mabokes", isAvailable: true },
  { id: "maboke-mabongo", name: "Maboké mabongo", slug: "maboke-mabongo", description: "Maboké préparé dans une riche sauce noire Mbongo aux épices traditionnelles torréfiées.", price: 9000, isPopular: true, imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80", categorySlug: "mabokes", isAvailable: true },
  { id: "sibissi", name: "Sibissi", slug: "sibissi", description: "Gibier Sibissi (Aulacode / Ratifa) mi-fumé sauté aux oignons verts et piment africain.", price: 7500, isPopular: true, imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "poisson-sale-aux-petits-legumes", name: "Poisson salé aux petits légumes", slug: "poisson-sale-aux-petits-legumes", description: "Makayabu (poisson salé) dessalé et mijoté aux tomates fraîches, oignons et petits légumes.", price: 6500, imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "poisson-sale-aux-aubergines", name: "Poisson salé aux aubergines", slug: "poisson-sale-aux-aubergines", description: "Poisson salé cuisiné avec des aubergines locales fondantes et huile de palme dorée.", price: 7000, imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "sanglier-saute", name: "Sanglier sauté", slug: "sanglier-saute", description: "Morceaux de sanglier de chasse sautés au vin rouge, ail, oignons et piment doux.", price: 9000, imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "bouillons-sauvage", name: "Bouillons sauvage", slug: "bouillons-sauvage", description: "Bouillon relevé et parfumé aux viandes de gibier sauvage de la région.", price: 8500, imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "bouillons-de-capitaine", name: "Bouillons de capitaine", slug: "bouillons-de-capitaine", description: "Soupe de poisson Capitaine mijotée avec citron vert, gingembre frais et piment.", price: 8000, imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "bouillons-de-mouton", name: "Bouillons de mouton", slug: "bouillons-de-mouton", description: "Bouillon succulent de viande de mouton tendre relevé aux condiments traditionnels.", price: 7500, imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "porc-epic", name: "Porc épic", slug: "porc-epic", description: "Spécialité rare de Porc-Épic cuisiné en sauce mijotée aromatique.", price: 9500, imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "viande-de-boeuf-sautee", name: "Viande de bœuf sautée", slug: "viande-de-boeuf-sautee", description: "Lamelles de bœuf tendres sautées au wok avec poivrons multicolores et oignons.", price: 6500, imageUrl: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "filet-de-boeuf-a-la-creme-fraiche", name: "Filet de bœuf à la crème fraîche", slug: "filet-de-boeuf-a-la-creme-fraiche", description: "Pavé de filet de bœuf nappé d'une sauce onctueuse à la crème fraîche et champignons.", price: 7500, imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "3-pieces-de-poisson", name: "3 pièces de poisson", slug: "3-pieces-de-poisson", description: "Trois darne de poissons frits croustillants servis avec sauce tomate aromatisée.", price: 7000, imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "ragout-de-mouton", name: "Ragoût de mouton", slug: "ragout-de-mouton", description: "Ragoût mijoté doucement au jus de cuisson, carottes et pommes de terre.", price: 7500, imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "saucisse", name: "Saucisse", slug: "saucisse", description: "Saucisses savoureuses poêlées servies chaudes avec oignons caramélisés.", price: 4500, imageUrl: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "darne-de-poisson", name: "Darne de poisson", slug: "darne-de-poisson", description: "Belle tranche de poisson braisée ou poêlée avec coulis de légumes.", price: 6500, imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "bouka", name: "Bouka", slug: "bouka", description: "Recette traditionnelle Bouka riche en saveurs et viandes sélectionnées.", price: 8000, imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
  { id: "porcelet", name: "Porcelet", slug: "porcelet", description: "Morceaux de porcelet rôti croustillant et fondant en bouche.", price: 9000, isPopular: true, imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80", categorySlug: "plats-cuisiniers", isAvailable: true },
];

export const dishes: Dish[] = [
  ...featuredDishes,
  ...additionalDishes.map(({ categorySlug, ...dish }) => ({
    ...dish,
    isPopular: dish.isPopular ?? false,
    category: categories.find((category) => category.slug === categorySlug),
  })),
];

export const popularDishes = dishes.filter((dish) => dish.isPopular).slice(0, 6);
